### ISSUE TITLE
Using serialization group for LIST, but not for GET results in empty columns instead of non existent columns

### ISSUE THREAD

**Issue by diimpp** [api-platform/admin#111]
Hi,

When I'm using serialization groups for `collectionOperations/get`, I'm expecting those fields not to appear in the view, instead I'm getting this fields with empty values.

Screenshot should illustrate the issue, empty columns are not really empty, but filtered with serialization group.
![screen shot 2018-08-04 at 11 18 57](https://user-images.githubusercontent.com/870747/43672447-4f353514-97d8-11e8-9d9c-d5f980a40f71.png)

my resource configuration 
```yaml
 App\Entity\Restaurant:
     collectionOperations:
         get:
             filters: ['restaurant.search_filter']
             normalization_context:
                 groups: ['restaurant:list']
         post: ~
     attributes:
         normalization_context:
             groups: ['restaurant']
         denormalization_context:
             groups: ['restaurant']
```

Serialization configuration

```yaml
 App\Entity\Restaurant:
     attributes:
         owner:
             groups: ['restaurant', 'restaurant:list']
         city:
             groups: ['restaurant', 'restaurant:list']
         specialities:
             groups: ['restaurant']
...
 
         name:
             groups: ['restaurant']
...
```
