### ISSUE TITLE
Server communication error when trying to retrieve or create entities

### ISSUE THREAD

**Issue by J4VMC** [api-platform/admin#136]
Hello,

I'm using the API component in a Symfony 4 project, as well as the Admin and Client components. I've followed the documentation on the website.

The API works great on `localhost:8000/api` and I access my Admin via `localhost:3000`.

My Nelmio Cors configuration is like

```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
```

The .env includes

```
###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
###< nelmio/cors-bundle ###
```

And my admin/src/App.js file in my Admin looks like

```
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';

export default () => <HydraAdmin entrypoint="http://localhost:8000/api"/>;
```

When I navigate to localhost:3000, the first time I can see the resources on the left and it throws an alert with `Server communication error` when I try to do any operations. The second time I access the Admin, it just says `Unable to retrieve API documentation.`.

Am I doing something wrong?
