### ISSUE TITLE
how to display 2 operations for collection on same entity using HydraAdmin

### ISSUE THREAD

**Issue by gomcodoctor** [api-platform/admin#248]
I have following config

```
App\Entity\Order:
  shortName:  'order'
  collectionOperations:
      get:
        method: 'GET'
        filters:  ['offer.date_filter', 'offer.order_filter']
      get_pending_order:
        method: 'GET'
        path: '/penidngorder'
```

I want to see list of pending orders as separate list, HydraAdmin ResourceGuesser not displaying it.

when I try to use

`<Resource name="penidngorder" />`

`Resource $penidngorder not present inside api description`

same issue if I try to manually set edit form using EditGuesser

what is correct way to do this?
