### ISSUE TITLE
Request causes error when an order filter is present on a resource

### ISSUE THREAD

**Issue by marcw** [api-platform/admin#25]
Hi!

First and foremost, thanks for your amazing work. You simplify the life of a lot of developers with your project. 

I have an api-platform app and just initialized an admin spa using this repository.

I have a `Contact` resource configured like this: 

```php
/**
 * Entity/Contact.php
 * 
 * @ApiResource(
 *     attributes={
 *         "filters"={"contact.order"},
 *         "normalization_context"={"groups"={"contact.get"}}
 *     }
 */
```

```yaml
# services.yml
services:
    contact.api.order_filter:
        autowire: false
        autoconfigure: false
        public: false
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{ createdAt: ~, updatedAt: ~, name: ~, email: ~, city: ~, country: ~, groups.group.name: ~ }]
        tags:
            - { name: 'api_platform.filter', id: 'contact.order' }
```

Fetching contacts from the `/api` endpoints works perfectly. However, the default admin client sends a request looking like this:
`http://localhost:8080/app_dev.php/api/contacts?sort=id&order=DESC&page=1`

which cause this error to happen:

```
Type error: Return value of 
ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter::extractProperties()
must be of the type array, string returned
```

Two issues here:

1. I believe the query parameter should be something like `order[id]=DESC`. 
2. Also, as I use UUID, I don't want `id` to be the default sort field. How can I tell the admin to sort by default on another field (like `createdAt`) ?
