### ISSUE TITLE
Pagination is not rendered

### ISSUE THREAD

**Issue by acidline** [api-platform/admin#34]
Hi,

Pagination works correctly in the Hydra parsing but she isn't rendered in listing view.

![image](https://user-images.githubusercontent.com/6313848/28578045-cbe23a46-7158-11e7-869e-fef84051c4c1.png)

In ApiPlatform, I specify pagination config like that : 

```yaml
api_platform:
    collection:
        pagination:
            items_per_page: 3
```
It seems that React props stay to 30 (default).

Can you confirm this report ? 

Nicolas
