### ISSUE TITLE
OpenAPI 3.1 nullable compatibility

### ISSUE THREAD

**Issue by lusimeon** [api-platform/admin#616]
**Description**  
OpenAPI 3.1 specification defines Schemas properties nullable types as described below [to follow JSON Schema 4](https://github.com/api-platform/core/issues/6803#issuecomment-2482346583).

API Platform Admin [schema Analyzer](https://github.com/api-platform/admin/blob/main/src/openapi/schemaAnalyzer.ts#L28) does not process nullable type and fallback to `string` type instead of extracting type from the non-nullable type. This introduces wrong input type when using Component like InputGuesser for example.

Schema Analyzer should take into account nullable types.

**Example**

```yaml
# OpenAPI specification example
[…]
properties:
    myProperty:
        type:
            - integer
            - null

# Before fix
schemaAnalyze field type is `string`

# After fix
schemaAnalyzer field type is `integer`
```
