### ISSUE TITLE
Unable to retrieve API documentation.

### ISSUE THREAD

**Issue by TangMonk** [api-platform/admin#73]
I am using the latest Symfony 4,  api-platform bundle, and following the documentation to setup api and admin

the api works(screenshot): 

![image](https://user-images.githubusercontent.com/3498786/33705598-e59c8072-db6b-11e7-808c-f516bcee9cf2.png)

the admin(screenshot):
![image](https://user-images.githubusercontent.com/3498786/33705482-76c0af02-db6b-11e7-83f6-8688e3972490.png)

And I disable the cors in chrome, but still not work

And I try to remove react and react-dom in package.json and yarn install agin, it still not work

**Comment by acidline** [comment]
Hi,

Do you have "Nelmio CORS Bundle" installed ?

If not, you must to add it : 

```
composer require "nelmio/cors-bundle:@dev"
```

It seems that add directly require bundle without @dev tag give compatbilities errors.
SF4 recipe is not now available.

Add bundle configuration inside "config/package/nelmio_cors.yaml" : 

```yaml
    nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']
```
After that, you can trick yout Nelmio CORS configuration.

Nicolas

**Comment by jorenvh1** [comment]
I have the same issue and I have Nelmio Cors enabled.
It's unclear for me which URL to use for the entrypoint in my react app...

Could you please explain if you have to enable any other settings (both on the api or the frontend) to make this work? @acidline

**Comment by vincentchalamon** [comment]
@TangMonk @jorenvh1 could you dump your `App.js` content please?

**Comment by jorenvh1** [comment]
@vincentchalamon 
```import React, { Component } from 'react';
import { HydraAdmin } from '@api-platform/admin';

export default class App extends Component {
  render() {
    return (
        <HydraAdmin entrypoint="http://symfony-3.dev"/>
    );
  }
}```

**Comment by vincentchalamon** [comment]
@jorenvh1 I guess http://symfony-3.dev is your local API entrypoint, and you have nelmio/cors correctly configured? You can use `*` as `nelmio_cors.default.allow_origin`

**Comment by jorenvh1** [comment]
@vincentchalamon Yeah, exactly, also cors are set up properly I think. When I look in my network tab, 2 calls are made.
First an OPTIONS call to that url, then a GET call to the same url. The GET call returns my /books endpoint but the frontend just shows me the text: 'Unable to retrieve API documentation'

**Comment by vincentchalamon** [comment]
Weird that your front can successfully call the API, but blocks on this error. Is the last GET call successful in your _Networks_ tab? Could you also try with a `curl http://symfony-3.dev/books`?

**Comment by jorenvh1** [comment]
Yep, last GET call is successful and returns my entrypoint for books.

**Comment by jorenvh1** [comment]
This is a screenshot of my network tab (I changed the domain to api-platform-api.dev)
![image](https://user-images.githubusercontent.com/14889143/33756923-0b975324-dbf8-11e7-98e6-ef7e65dc3089.png)

**Comment by andreluizlunelli** [comment]
Hi, first of all, aweome project!

Get the same error.
![cors](https://user-images.githubusercontent.com/16464118/33773480-23a5a2dc-dc1f-11e7-9188-232dcd5425aa.PNG)

`localhost/:1 Failed to load http://localhost:8080/: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://localhost:3000' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Running project with configs:
* php 7.1
* Symfony 3.3.13 
* parameters.yml with cors_allow_origin: '*'
* App.js with entrypoint http://localhost:8080

http://localhost:8080/ run api properly

I'm newbie in Symfony =/

Can someone help me?

**Comment by andreluizlunelli** [comment]
Hi,

I add a `add_header 'Access-Control-Allow-Origin' '*';` on default.conf file, build docker image, run and works!

**Comment by jorenvh1** [comment]
Hey @andreluizlunelli The cors headers are set to '*' for me as well, just as a test. The api call actually works so I'm still uncertain as to why it still gives me the error...

**Comment by andreluizlunelli** [comment]
@jorenvh1 
I believe that works for GET method, but not for POST.
You set that option(image) on nginx?
![cors-nginx](https://user-images.githubusercontent.com/16464118/33826720-0eeaa132-de4d-11e7-81ff-c583893788a2.PNG)

**Comment by jorenvh1** [comment]
@andreluizlunelli I set these headers in my symfony api with the nelmio CORS package (https://github.com/nelmio/NelmioCorsBundle)

**Comment by jorenvh1** [comment]
I had to add the 'Link' header to the expose_headers array in my NelmioCors config to fix this issue ;)

**Comment by maximeag** [comment]
Hi everyone,

I tried to use api-platform/admin with the official example at [https://demo.api-platform.com/](https://demo.api-platform.com/) and I got the same error : **Unable to retrieve API documentation.**

<img width="639" alt="capture d ecran 2017-12-20 a 15 44 25" src="https://user-images.githubusercontent.com/3855368/34212516-cc751894-e59c-11e7-8da9-36189a113040.png">

**Comment by decebaldecebal** [comment]
I have the same error and my cors configuration is correct.
The app makes two calls to my backend, one OPTIONS and one GET and the get returns this:

![screenshot from 2018-01-23 12-27-21](https://user-images.githubusercontent.com/6453351/35270821-e6e8f964-0038-11e8-913c-c8959bf3289b.png)

But the React app does not want to work.I am using Symfony 4 and the default Api Platform Admin configuration.

**Comment by piela** [comment]
Solved. Admin app use https://localhost:8443 to connect to api . Open  https://localhost:8443 url in your browser and accept the security risk. Done.

**Comment by lethak** [comment]
I fixed the original issue with this config

```yaml
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: ['Content-Disposition', 'Content-Length', 'Link']
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 120
        '^/': ~

```

notice that `expose_header` has `Link`

**Comment by alexislefebvre** [comment]
I had the same error, I took several ideas but the main problem was that I didn't opened a `GET` endpoint for listing items.

So, if you have the same error, check that you have something like this in your configuration:

```yml
App\Entity\Delivery:
    attributes:
        # …
    itemOperations:
        # …
    collectionOperations:
        get:
            method: 'GET'
```

It looks like the admin perform requests in order to fetch every endpoint.

**Comment by luispabon** [comment]
I'm experiencing the same problem, but I see no errors anywhere:

![image](https://user-images.githubusercontent.com/6388823/41114247-c4d041e0-6a7b-11e8-808c-864a4bea5850.png)

![image](https://user-images.githubusercontent.com/6388823/41114306-f86c505c-6a7b-11e8-9738-3ffe45d62250.png)

There's nothing on the javascript console, and CORS is correctly configured and working. The admin app is indeed retrieving the docs, getting them, and then erroring out.

**Comment by dunglas** [comment]
Can you also try to run https://github.com/api-platform/api-platform-doc-parsing-check?

**Comment by luispabon** [comment]
@dunglas 

```
api-platform-parsing-check ~ node_modules/@api-platform/api-platform-doc-parsing-check/lib/index.js http://localhost:13000/api

Checking documentation parsing for API @ http://localhost:13000/api
[ 'books', 'reviews' ]
Number of endpoints parsed : 2
```

**Comment by luispabon** [comment]
On fetchJson I only see one request, of which this is the response:

![image](https://user-images.githubusercontent.com/6388823/41153706-75cdb0de-6b0f-11e8-800b-d9061435d8c3.png)

The request in question (response on my previous post) does have cors headers and stuff, they all seem to check out

![image](https://user-images.githubusercontent.com/6388823/41153814-d2d32fde-6b0f-11e8-99a5-cbfa5eb8c606.png)

**Comment by luispabon** [comment]
AHA. Expose headers > "links" instead of "link".  I didn't copy it correctly from here. 

It might be worth updating api platform's and admin's documentations on this regard. API Platform's zip distribution has the correct nelmio cors config, but I didn't install it like that. I simply required `api` on a pre-existing symfony flex app.

**Comment by stepotronic** [comment]
I think I will just leave it here:
If you are working with the docker version, make sure you visited https://localhost:8443/ once and accepted the certificate, otherwise it won't work even if you adjusted all of the configs.

**Comment by jorr-it** [comment]
Since this thread comes up high on search engines, let me leave the solution that worked for me. If you installed API Platform without Docker, you need to expose header Link in your Nelmio CORS configuration, as 
 [explained here](https://stackoverflow.com/a/50428448/2366136).

**Comment by numediaweb** [comment]
What worked for me is:
```
#my-app/admin/src/App.js
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';

export default () => <HydraAdmin entrypoint="https://my-app-microservice.dev/api"/>;

```
Because I my book entity is in this path: https://my-app.dev/api/book
```
#my-app-microservice/app/config/config.yml
nelmio_cors:
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
```
